CREATE TABLE APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50)
);



CREATE TABLE DOCUMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(1000),
    HASH VARCHAR(255),
    AGREE BOOLEAN DEFAULT FALSE,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE MEMORY TABLE "PUBLIC"."LEAVE_APPLICATIONS"(

    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,

    "CERTIFICATE_HASH" CHARACTER VARYING(255),

    "CLINIC_ADDRESS" CHARACTER VARYING(255),

    "CLINIC_NAME" CHARACTER VARYING(255),

    "CONFIDENCE_SCORE" INTEGER,

    "CONTACT_NUMBER" CHARACTER VARYING(255),

    "CREATED_AT" TIMESTAMP,

    "DATE_OF_ISSUE" CHARACTER VARYING(255),

    "DOCTOR_NAME" CHARACTER VARYING(255),

    "EMPLOYEE_ID" CHARACTER VARYING(255),

    "FILE_NAME" CHARACTER VARYING(255),

    "LEAVE_DATES" CHARACTER VARYING(255),

    "MC_NUMBER" CHARACTER VARYING(255),

    "PATIENT_NAME" CHARACTER VARYING(255),

    "QR_CODE_PRESENT" BOOLEAN,

    "QR_CODE_URL" CHARACTER VARYING(255),

    "REASON" CHARACTER VARYING(255),

    "REGISTRATION_ID" CHARACTER VARYING(255),

    "REMARKS" CHARACTER VARYING(255),

    "RESULT_DETAILS" CHARACTER VARYING(255),

    "STATUS" CHARACTER VARYING(255),

    "SYSTEM_SUGGESTION" CHARACTER VARYING(255)

);

DELETE FROM APP_USER;

INSERT INTO APP_USER (id, username, password, role) VALUES (
  1,
  '165468',
  '$2a$12$E7nT9DqIKi9UpKtWSJY.Oe2Q4a7f3ZYl5TI9WyeFBlGDwofAgs562',  -- ← admin123
  'ADMIN'
);


INSERT INTO "PUBLIC"."LEAVE_APPLICATIONS" VALUES

(1, '30b319f56261db532225145bf7cef654cf43be9c43cb12124f130e4958280801', '7th St, New York, NY 114, USA [Of=H0', 'Qj St. Claire Clinic', 90, '832-090-1874 5,', TIMESTAMP '2026-02-04 13:14:40.23', '01/09/2023 - 2:40 PM Discharged: 10/09/2023 - 5:00 PM', 'Dr. Emily Clark Phone: 832-090-1874 5,', '165468', '1770191080230_Medical_Certificate.png', '2026-02-05 to 2026-02-06', 'info@stclaireclinic.com [m]3EE=', 'Raymond Ward Patient ID: 13894-32482', FALSE, NULL, 'Sick ', '13894-32482', 'No duplicate certificate detected. Missing mandatory fields: QR Code. Certificate is not marked invalid. Certificate is not used by anyone else. QR code is missing or invalid.', 'QR code missing or invalid.', 'PENDING', 'Approve'),

(2, '5f060be3fa4b2a597b69612bdf6578f00201d3b75cae6a3a4fb84419e9c6dbc0', '7th St, New York, NY 114, USA B % ol', '@ St. Claire Clinic', 100, '832-090-1874 &.', TIMESTAMP '2026-02-04 13:19:31.844', '01/09/2023 - 240 PM Discharged: 10/09/2023 - 500 PM', 'Dr. Emily Clark Phone: 832-090-1874 &.', '165468', '1770191371835_Medical_Certificate with QR.png', '2026-02-11 to 2026-02-13', 'info@stclaireclinic.com &', 'Raymond Ward Patient ID: 1389432482', TRUE, 'https://www.st-claire.org/', 'Leave', '1389432482', 'No duplicate certificate detected. All mandatory fields including QR code are present. Certificate is not marked invalid. Certificate is not used by anyone else. QR code is present with valid URL.', '', 'PENDING', 'Approve'),

(3, 'd100ec0a72ff232aa0283cb93329f67c965b45870caf1b0323348b5b87128e8a', NULL, NULL, 30, NULL, TIMESTAMP '2026-02-04 13:20:34.881', NULL, NULL, '165468', '1770191434863_MC_PDF.pdf', '2026-02-17 to 2026-02-19', NULL, NULL, FALSE, NULL, 'Leave', NULL, 'Certificate is invalid. Most required information is missing.', '6 mandatory fields missing. QR code missing or invalid.', 'PENDING', 'Reject'),

(4, '47c2d388134f150c8b227acc499b205553a61bcaf377fb3b98dcca1f9c71e044', 'Plot 12, Tech Park Road, Madhapur, Hyderabad, Telangana 500081', 'Sunrise Multispeciality Hospital', 90, '+91 40 1234 5678', TIMESTAMP '2026-02-04 13:21:46.436', '05 August 2025', 'Dr. A. Meera, MD (Internal Medicine), Reg. No. TS-IM-43921', '165468', '1770191506429_Discharge_Certificate_SH-2025-0805-7842.pdf', '2026-02-19 to 2026-02-25', 'records@sunrisehosp.test', 'Rahul Sharma', FALSE, NULL, 'Sick Leave', 'P-2025-08-00231', 'No duplicate certificate detected. Missing mandatory fields: QR Code. Certificate is not marked invalid. Certificate is not used by anyone else. QR code is missing or invalid.', 'QR code missing or invalid.', 'PENDING', 'Approve');
